spring:
  application:
     name: eureka-server
server:
  port: 8093
eureka: 
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://localhost:8093/eureka